### ISSUE TITLE
Temporary agenda issue

### ISSUE THREAD

**Issue by Manishearth** [nrc/dev-tools-team#46]
We don't have a meeting time set yet, however I need a place to jot down things that devtools needs to discuss:

 - rehash discussion about role of team
 - how to deal with small tools like semverver
 - go through all smaller tools and just check up on their maintainership (maybe not during meeting itself)
 - how to find and address tool vacuums
 - the role of this Github org

feel free to add more!

**Comment by killercup** [comment]
Would be great to have some ideas and proposals ready for the meeting! Especially addressing tool vacuums and providing support for smaller tools are topics that require both ideas on how to facilitate this in general as well as concrete actions for specific tools we can take as team.

cc @Xanewok, @fitzgen, @GuillaumeGomez, @oli-obk, @dwijnand

**Comment by GuillaumeGomez** [comment]
For finding vacuum, I wonder if that should come from us or from Rust users directly. Well, I suppose we can already feel a part of it by ourselves but the remainings might require a broader participation.

**Comment by Manishearth** [comment]
Oh, this is totally about figuring out _how_ to find vacuums, not actually
finding them. So running a survey or something is a part of this.

**Comment by GuillaumeGomez** [comment]
Makes sense.
